---
title: "routinediff_milan_cleaning"
author: "rmilan"
date: "2024-05-02"
output: html_document
---

```{r run assoc libraries}
library(ggplot2)
library(dplyr)
library(haven)
library(car)
library(coefplot)
library(nnet)
library(knitr)
library(survey)
```


```{r create sample dataset}
samptot <- c19cs_soceduexe %>% 
  filter(!is.na(edu_diff), !is.na(t36_cesd_tot), !is.na(t36_anx_tot), !is.na(t36_lonely_tot), !is.na(exe_diff), !is.na(soc_diff), !is.na(pop_attwf36m)) ## Sample size= 1,824

```



```{r data cleaning}
## Exercise Routine diffs
samptot$exe_difflab <- factor(samptot$exe_diff, levels = c(0,1), labels= c("No","Yes"), exclude=NULL)
table(samptot$exe_difflab, samptot$exe_diff)

## Social Routine diffs
samptot$soc_difflab <- factor(samptot$soc_diff, levels = c(0,1), labels= c("No","Yes"), exclude=NULL)
table(samptot$soc_difflab, samptot$soc_diff)

## Education Routine diffs
samptot$edu_difflab <- factor(samptot$edu_diff, levels = c(0,1), labels= c("No","Yes"), exclude=NULL)
table(samptot$edu_difflab, samptot$edu_diff)

## Sex
samptot$sex_lab <- factor(samptot$sex_36, levels = c(0,1, 2, 3), labels= c("Male","Female", "Other", "Prefer not to answer"), exclude=NULL)
table(samptot$sex_lab, samptot$sex_36)

## Race
samptot$race_lab <- factor(samptot$racialized_36, levels = c(1, 2, 3, 4, 5, 6, 7), labels= c("NH White","NH Black", "Hispanic or Latinx", "East Asian or Native Hawaiian or Other Pacific Islander", "American Indian or Alaska Native", "Asian Indian", "Other"), exclude=NULL)
table(samptot$racialized_36, samptot$race_lab)

## Relationship status
samptot$relat_lab <- factor(samptot$relat36m, levels = c(1, 2, 3, 4, 5), labels= c("single, never married", "single, divorced/separated", "single, widowed", "married or in a relationship", "other"), exclude=NULL)
table(samptot$relat_lab, samptot$relat36m)

## Education level
samptot$educ_lab <- factor(samptot$educ_36, levels = c(1, 2, 3, 4, 5,6), labels= c("less than high school", "high school diploma", "high school equivalent", "some college", "college graduate", "graduate school"), exclude=NULL)
table(samptot$educ_lab, samptot$educ_36)

##Employment Status
samptot$emp_lab <- factor(samptot$emp_36m, levels = c(0, 1, 2, 3, 4, 5), labels= c("Not working", "working", "in school", "retired", "homemaker", "other"), exclude=NULL)
table(samptot$emp_lab, samptot$emp_36m)

## Moved since baseline
samptot$moved_lab <- factor(samptot$moved_36, levels = c(0,1), labels= c("No","Yes"), exclude=NULL)
table(samptot$moved_36, samptot$moved_lab)

```

```{r mental health variables}


## Loneliness categorical variable
# Create multi-categorical variable
breaks<- c(2, 5, 7, 9)
samptot$lonely_catlab <- cut(samptot$t36_lonely_tot, breaks = breaks, labels= c("Hardly Ever lonely", "Some of the time lonely", "Often lonely"))
table(samptot$lonely_catlab, samptot$t36_lonely_tot)

breaks<- c(2, 5, 7, 9)
samptot$lonely_cat <- cut(samptot$t36_lonely_tot, breaks = breaks, labels= c(0, 1, 2))
table(samptot$lonely_cat, samptot$lonely_catlab)

# Create loneliness binary-categorical variable
breaks_lonely <- c(2,5,9) 
samptot$lonely_bin <- cut(samptot$t36_lonely_tot, breaks=breaks_lonely, labels= c(0,1))
table(samptot$lonely_bin, samptot$t36_lonely_tot)
table(samptot$lonely_bin)

samptot$lonely_bincat <- 

### 0= "Hardly ever lonely"
### 1= "lonely some of the time or often"
### https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8285042/

## anxiety multi-categorical variable
samptot$t36_anx_catlab <- factor(samptot$t36_anx_cat, levels = c(0,1,2), labels= c("Normal/No anxiety","Mild/Moderate anxiety", "Severe anxiety"), exclude=NULL)

## anxiety binary categorical variable
breaks_anx <- c(-1,0,2)
samptot$t36_anx_bin <- cut(samptot$t36_anx_cat, breaks=breaks_anx, labels = c(0,1))
table(samptot$t36_anx_bin, samptot$t36_anx_cat)
table(samptot$t36_anx_bin)

## Label cesd categorical variable
samptot$t36_cesd_catlab <- factor(samptot$t36_cesd_cat, levels = c(0,1), labels= c("Little to no depressive symptoms","Has depressive symptoms"), exclude=NULL)
table(samptot$t36_cesd_catlab, samptot$t36_cesd_cat)

## CES-D binary variable
breaks_dep <- c(-1,0,1)
samptot$t36_cesd_bin <- cut(samptot$t36_cesd_cat, breaks=breaks_dep, labels = c(0,1))
table(samptot$t36_cesd_bin, samptot$t36_cesd_cat)
table(samptot$t36_cesd_bin)

# Create combined binary mental health variable with anxiety and depression only, multicategorical (any anx or dep symptoms)
samptot$anxdep_combo <- paste(samptot$t36_anx_cat, samptot$t36_cesd_cat, sep = "_")
table(samptot$anxdep_combo)
samptot$anxdep_combo2 <- paste(samptot$t36_anx_cat, samptot$t36_cesd_cat, sep = "_")

samptot <- samptot %>%
  mutate(anxdep_combo = case_when(
    anxdep_combo == "0_0" ~ 0,
    anxdep_combo== "0_1" ~ 1,
    anxdep_combo == "1_0" ~ 1,
    anxdep_combo== "1_1" ~ 1,
    anxdep_combo== "2_1" ~ 1,
    anxdep_combo== "2_0" ~ 1))
table(samptot$anxdep_combo, samptot$anxdep_combo2)
## Dropped missing values because less than 5% of sample

## Label anx/dep combo variable
samptot$anxdep_combo <- factor(samptot$anxdep_combo, levels = c(0,1), labels= c("No ","Yes"), exclude=NULL)
table(samptot$anxdep_combo)

## NA values were dropped as missing since less than 5% of sample


```

```{r save dataset for descriptives and analysis}
write.csv(samptot, "samptot_clean.csv", row.names = FALSE) ##analytic sample file
```





